CREATE TABLE TC_MASTER (
    TC_ID VARCHAR(50) PRIMARY KEY,
    TC_NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(255),
    FLAG VARCHAR(20) NOT NULL,
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP
);

CREATE TABLE PARAMETER_SCHEMA (
    SCHEMA_ID VARCHAR(100) PRIMARY KEY,
    SCHEMA_VERSION INT NOT NULL,
    SCHEMA_DEFINITION TEXT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    DESCRIPTION VARCHAR(255),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP,
    UNIQUE (SCHEMA_ID, SCHEMA_VERSION)
);

CREATE TABLE STEP_CONFIG (
    STEP_NAME VARCHAR(100) PRIMARY KEY,
    DESCRIPTION VARCHAR(255),
    TIMEOUT_SECONDS INT NOT NULL DEFAULT 300,
    MAX_RETRIES INT NOT NULL DEFAULT 3,
    PARAMETER_SCHEMA VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP,
    FOREIGN KEY (PARAMETER_SCHEMA) REFERENCES PARAMETER_SCHEMA(SCHEMA_ID)
);

CREATE TABLE STEP_SCHEMA_MAPPING (
    STEP_NAME VARCHAR(100),
    SCHEMA_ID VARCHAR(100),
    IS_REQUIRED BOOLEAN DEFAULT TRUE,
    SEQUENCE_NO INT NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (STEP_NAME, SCHEMA_ID),
    FOREIGN KEY (STEP_NAME) REFERENCES STEP_CONFIG(STEP_NAME),
    FOREIGN KEY (SCHEMA_ID) REFERENCES PARAMETER_SCHEMA(SCHEMA_ID)
);

CREATE TABLE TC_STEPS (
    STEP_ID INT,
    TC_ID VARCHAR(50),
    STEP_NAME VARCHAR(100) NOT NULL,
    PARAMETERS TEXT,
    SEQUENCE_NO INT NOT NULL,
    STATUS VARCHAR(20),
    PRIMARY KEY (STEP_ID, TC_ID),
    FOREIGN KEY (TC_ID) REFERENCES TC_MASTER(TC_ID),
    FOREIGN KEY (STEP_NAME) REFERENCES STEP_CONFIG(STEP_NAME)
);

CREATE TABLE TC_EXECUTION_LOG (
    EXECUTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TC_ID VARCHAR(50),
    STEP_ID INT,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    STATUS VARCHAR(20),
    ERROR_MESSAGE TEXT,
    FOREIGN KEY (TC_ID) REFERENCES TC_MASTER(TC_ID)
);

-- Create indexes
CREATE INDEX idx_tc_master_flag ON TC_MASTER(FLAG);
CREATE INDEX idx_tc_steps_tcid ON TC_STEPS(TC_ID);
CREATE INDEX idx_execution_log_tcid ON TC_EXECUTION_LOG(TC_ID);
CREATE INDEX idx_parameter_schema_active ON PARAMETER_SCHEMA(IS_ACTIVE);
